### ISSUE TITLE
Doesn't work with radon 6.0.1

### ISSUE THREAD

**Issue by Sterh20** [cdein/python-radon#5]
Tried to use the extension with the latest radon package (6.0.1), but the extension kept spamming 

> "You need to install python-radon at a minimum version 5.1: pip install "radon>=5.1"

Also cyclomatic complexity wasn't showing in the .py files.

After installing radon version 5.1 the issue resolved itself.

------------------------------
Windows 10 Pro 10.0.19045
VS Code 1.78.2
Python 3.10.11

**Comment by ghost** [comment]
Managed to reproduce this on Windows 11, Python 3.11.4, VS Code 1.78.2. Installing 5.1 fixes the issue.

**Comment by Drache91** [comment]
I suppose it is this line causing the version check confusion:
https://github.com/cdein/python-radon/blob/af0b4c91a3648c96c62ce3fc637fca62d3cbd5b4/src/RadonProvider.ts#L78
```ts
            if (major < 5 || minor < 1) {
                throw new UnsupportedVersionException("You need at least python radon version 5.1 installed. Try pip install \"radon>=5.1\".");
            }
```
Should fix itself with a radon version that has the minor version >= 1. But I think the version check should be fixed.

**Comment by DerekCL** [comment]
Still, an issue as of today since the fix was merged in July of 2023( as you can see from above) but the last released in the vs code store was:


Last released
2022-02-28, 15:15:22

**Comment by dylan-robins** [comment]
Still facing this issue today. @cdein, any plans on releasing the fix on the vscode marketplace any time soon? I'd like to promote the use of this in my company as it's a really useful tool...

**Comment by nickweedon** [comment]
I too would like to see this released. In the meantime you can actually create a simple wrapper script to intercept a call to the binary with the '-v' argument and then perform a proper check and just return 5.2 if the version really is >=5.1.

**Comment by adminROBIOTEC** [comment]
Still an issue...

**Comment by igoutta** [comment]
Still doesn't work. Getting into vscode-radon-linter.

**Comment by Luispain** [comment]
Hi all,

As of today, facing this issue also in Rocky Linux 8.7, Python 3.8.14 being installed and used remotely (ssh remote) from a Windows 10 and vs code 1.71.2

Downgrading radon to 5.1 version fixes the issue
